<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>mustache</string>
	</array>
	<key>name</key>
	<string>Mustache (HTML)</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#variables</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#partials</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#blocks</string>
		</dict>
		<dict>
			<key>include</key>
			<string>text.html.basic</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>blocks</key>
		<dict>
			<key>begin</key>
			<string>\{\{\s*(#|\^)[A-Za-z0-9_.]+\s*\}\}</string>
			<key>end</key>
			<string>\{\{/[A-Za-z0-9_.]+\}\}</string>
			<key>name</key>
			<string>entity.name.tag.mustache</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variables</string>
				</dict>
				<dict>
					<key>include</key>
					<string>text.html.basic</string>
				</dict>
				<dict>
					<key>match</key>
					<string>.</string>
					<key>name</key>
					<string>string.unquoted.mustache</string>
				</dict>
			</array>
		</dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\{\{!\s*([A-Za-z0-9_.?]+)\s*\}\}</string>
					<key>name</key>
					<string>comment.mustache</string>
				</dict>
			</array>
		</dict>
		<key>partials</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\{\{&gt;\s*([A-Za-z0-9_.?]+)\s*\}\}</string>
					<key>name</key>
					<string>keyword.operator.mustache</string>
				</dict>
			</array>
		</dict>
		<key>variables</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\{\{\{\s*([A-Za-z0-9_.?]+)\s*\}\}\}</string>
					<key>name</key>
					<string>entity.name.tag.mustache</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\{\{\s*([A-Za-z0-9_.?]+)\s*\}\}</string>
					<key>name</key>
					<string>entity.name.tag.mustache</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.mustache</string>
	<key>uuid</key>
	<string>93706aaa-9b66-4e9e-bb64-31a8ffcfb00d</string>
</dict>
</plist>
